### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by RodriguezLucha** [RodriguezLucha/zelpfullstack#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by evhumphrey** [comment]
Looks good! Here's some feedback (mostly styling to match closer to yelp): 

### Bug
- [ ] Make sure to clear your errors between forms (ex: if you submit a blank form on log in, then navigate to sign up, the errors are still there)
- [ ] Relatedly, when your errors are styled, there's a little x to clear them on yelp. Make sure to implement this (you would dispatch your clear error action when you click on this button)

### Forms
- [ ] Style your errors (they should be at top of page like yelp) 
- [ ] Increase the height of the inputs a bit
- [ ] Decrease left/right padding of inputs a bit
- [ ] Decrease font size of inputs
- [ ] Lighten the color of "Connect with great local restaurants" and "New to Zelp"
- [ ] Add `cursor: pointer` to your buttons

### Splash
- [ ] I'd make your element with class home a bit taller (increase height) so the image takes up a bit more space

### Nav 
- [ ] The transitions on hovering for demo and sign up are mismatched -- make sure they are the same
- [ ] Push the nav bar a bit down
- [ ] Increase left/right padding on the nav links a bit
- [ ] Increase the margins between nav links a bit
- [ ] Change "Login" to "Log In"

Image of what the form should look like
![screen shot 2019-03-01 at 11 41 30 am](https://user-images.githubusercontent.com/6361824/53662192-2e499780-3c17-11e9-819d-40528c5af170.png)

**Comment by RodriguezLucha** [comment]
~Make sure to clear your errors between forms (ex: if you submit a blank form on log in, then navigate to sign up, the errors are still there)~
~I'd make your element with class home a bit taller (increase height) so the image takes up a bit more space~
~The transitions on hovering for demo and sign up are mismatched -- make sure they are the same~
~Change "Login" to "Log In"~

**Comment by evhumphrey** [comment]
👍
