### ISSUE TITLE
PA Review: Restaurant Show Page

### ISSUE THREAD

**Issue by RodriguezLucha** [RodriguezLucha/zelpfullstack#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by evhumphrey** [comment]
What is the route for viewing restaurants (have you pushed these changes to heroku?)

**Comment by RodriguezLucha** [comment]
Oops, I forgot to run db:migrate and db:seed, it should work now. You can get there via top restaurants and I also deployed the search feature

**Comment by RodriguezLucha** [comment]
Also food pictures are pulling from S3!

**Comment by RodriguezLucha** [comment]
Everything ready to go, all MVPs completed.
